import { useState, useEffect } from 'react';
import { backendWalletService, BackendWallet } from '../services/backendWallet';
import { ethers } from 'ethers';
import { useSelector } from 'react-redux';
import { RootState } from '../services/store';
import { getMultipleTokenPrices } from '../services/cryptoPrice';

export const useBackendWallet = () => {
  const [isConnected, setIsConnected] = useState(false);
  const [address, setAddress] = useState<string | null>(null);
  const [balances, setBalances] = useState<Record<string, number>>({});
  const [usdValues, setUsdValues] = useState<Record<string, number>>({});
  const [totalBalanceUsd, setTotalBalanceUsd] = useState<number>(0);
  const [isLoading, setIsLoading] = useState(false);
  const [isLoadingBalances, setIsLoadingBalances] = useState(false);
  
  // Get wallet address from user profile state (generated by backend)
  const profile = useSelector((state: RootState) => state.user.profile);
  const walletAddress = profile?.walletAddress;
  console.log('walletAddress', walletAddress);

  // Only these 9 tokens are supported - show with 0 balances when wallet is empty
  const POPULAR_BSC_FALLBACK =  [
    { symbol: 'MARS', name: 'MARS Token', address: '0x6844B2e9afB002d188A072A3ef0FBb068650F214', decimals: 18, logoURI: 'https://cdn.dexscreener.com/cms/images/d33c76a1c7bb23e4de0e83553377c191453dfc36f114393a0e012ea509060908?width=128&height=128&fit=crop&quality=95&format=auto' }, // TODO: Replace with actual MARS address and logo
    { symbol: 'BNB', name: 'BNB', address: 'native', decimals: 18, logoURI: '' }, // Logo fetched from DexScreener
    { symbol: 'WKC', name: 'WKC Token', address: '0x6Ec90334d89dBdc89E08A133271be3d104128Edb', decimals: 18, logoURI: 'https://cdn.dexscreener.com/cms/images/6012b7aeac14fd99318f10747e4deb40c0de61588e12e873621e354f4033a513?width=128&height=128&fit=crop&quality=95&format=auto' }, // Logo fetched from DexScreener
    { symbol: 'DTG', name: 'DTG Token', address: '0xb1957bdba889686ebde631df970ece6a7571a1b6', decimals: 18, logoURI: 'https://cdn.dexscreener.com/cms/images/86ab901bc71e3cf982bc8f6a429cd28a5e0895b1cd8472f6460d490a552f7975?width=128&height=128&fit=crop&quality=95&format=auto' }, // Logo fetched from DexScreener
    { symbol: 'YUKAN', name: 'YUKAN Token', address: '0xd086B849a71867731D74D6bB5Df4f640de900171', decimals: 18, logoURI: 'https://cdn.dexscreener.com/cms/images/97292f8e15e0dcf3da3cd28698b8810870ba938cf15b5e78fa68346b3116e61e?width=128&height=128&fit=crop&quality=95&format=auto' }, // Logo fetched from DexScreener
    { symbol: 'TWD', name: 'TWD Token', address: '0xf00cd9366a13e725ab6764ee6fc8bd21da22786e', decimals: 18, logoURI: 'https://cdn.dexscreener.com/cms/images/8ea0e9c58e403cf520a9a02572a433bfcc9e41dff9c79d83b599e4110cd2d449?width=128&height=128&fit=crop&quality=95&format=auto' }, // Logo fetched from DexScreener
    { symbol: 'TKC', name: 'TKC Token', address: '0x06dc293c250e2fb2416a4276d291803fc74fb9b5', decimals: 18, logoURI: 'https://cdn.dexscreener.com/cms/images/d940f694d43867e42d75d6b751930f1bf34f140acc8e5c22dd4c051d47434132?width=128&height=128&fit=crop&quality=95&format=auto' }, // Logo fetched from DexScreener
    { symbol: 'ETH', name: 'Ethereum Token', address: '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', decimals: 18, logoURI: 'https://cdn.dexscreener.com/fetch?src=https%3A%2F%2Fcoin-images.coingecko.com%2Fcoins%2Fimages%2F39580%2Flarge%2Fweth.png%3F1723006716' }, // Logo fetched from DexScreener
    { symbol: 'USDT', name: 'Tether USD', address: '0x55d398326f99059fF775485246999027B3197955', decimals: 18, logoURI: '' } // Logo fetched from DexScreener
  ];

  // Fetch token list from PancakeSwap API
  const fetchTokenList = async () => {
    try {
      const response = await fetch('https://tokens.pancakeswap.finance/pancakeswap-bnb-mm.json');
      const data = await response.json();
      
      // Convert to our format and add native BNB
      const tokens = data.tokens.map((token: any) => ({
        symbol: token.symbol,
        name: token.name,
        address: token.address,
        decimals: token.decimals,
        logoURI: token.logoURI
      }));
      
      // Add native BNB
      tokens.unshift({
        symbol: 'BNB',
        name: 'BNB',
        address: 'native',
        decimals: 18,
        logoURI: '' // Logo fetched from DexScreener
      });
      
      return tokens;
    } catch (error) {
      console.error('Failed to fetch token list:', error);
      // Fallback to only the 9 supported tokens
      return [
        { symbol: 'MARS', name: 'MARS Token', address: '0x6844B2e9afB002d188A072A3ef0FBb068650F214', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png' }, // TODO: Replace with actual MARS address and logo
        { symbol: 'BNB', name: 'BNB', address: 'native', decimals: 18, logoURI: '' }, // Logo fetched from DexScreener
        { symbol: 'WKC', name: 'WKC Token', address: '0x6Ec90334d89dBdc89E08A133271be3d104128Edb', decimals: 18, logoURI: '' }, // Logo fetched from DexScreener
        { symbol: 'DTG', name: 'DTG Token', address: '0xb1957bdba889686ebde631df970ece6a7571a1b6', decimals: 18, logoURI: '' }, // Logo fetched from DexScreener
        { symbol: 'YUKAN', name: 'YUKAN Token', address: '0xd086B849a71867731D74D6bB5Df4f640de900171', decimals: 18, logoURI: '' }, // Logo fetched from DexScreener
        { symbol: 'TWD', name: 'TWD Token', address: '0xf00cd9366a13e725ab6764ee6fc8bd21da22786e', decimals: 18, logoURI: '' }, // Logo fetched from DexScreener
        { symbol: 'TKC', name: 'TKC Token', address: '0x06dc293c250e2fb2416a4276d291803fc74fb9b5', decimals: 18, logoURI: '' }, // Logo fetched from DexScreener
        { symbol: 'ETH', name: 'Ethereum Token', address: '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', decimals: 18, logoURI: '' }, // Logo fetched from DexScreener
        { symbol: 'USDT', name: 'Tether USD', address: '0x55d398326f99059fF775485246999027B3197955', decimals: 18, logoURI: '' } // Logo fetched from DexScreener
      ];
    }
  };

  // Fetch real balances from BSC with dynamic token detection
  const fetchRealBalances = async () => {
    if (!address) {
      setIsLoadingBalances(false);
      return;
    }
    
    setIsLoadingBalances(true);
    console.log('Starting balance fetch for address:', address);
    
    // Set a timeout to prevent infinite loading
    const timeoutId = setTimeout(() => {
      console.warn('Balance fetch timeout, setting loading to false');
      setIsLoadingBalances(false);
      setBalances({});
    }, 20000); // 20 second timeout - reduced to prevent long waits
    
    try {
      // Fetch token list from PancakeSwap with timeout
      const tokenListPromise = fetchTokenList();
      const tokenListTimeout = new Promise((_, reject) => 
        setTimeout(() => reject(new Error('Token list fetch timeout')), 10000)
      );
      
      const tokenList = await Promise.race([tokenListPromise, tokenListTimeout]) as any[];
      console.log('Fetched token list:', tokenList.length, 'tokens');
      
      // Use a reliable BSC RPC endpoint
      const provider = new ethers.JsonRpcProvider('https://bsc-dataseed.bnbchain.org/');
      
      // Test connection first with timeout
      try {
        await Promise.race([
          provider.getBlockNumber(),
          new Promise((_, reject) => setTimeout(() => reject(new Error('RPC timeout')), 5000))
        ]);
        console.log('Connected to BSC RPC');
      } catch (error) {
        console.error('Failed to connect to BSC RPC:', error);
        throw new Error('Failed to connect to blockchain');
      }
      
      const newBalances: Record<string, number> = {};
      const ERC20_ABI = [
        "function balanceOf(address) view returns (uint256)",
        "function decimals() view returns (uint8)"
      ];
      
      // Process tokens in batches to avoid overwhelming the RPC
      const batchSize = 5; // Reduced batch size
      const maxBatches = 4; // Limit to first 20 tokens to prevent timeout
      const tokensToCheck = tokenList.slice(0, batchSize * maxBatches);
      
      for (let i = 0; i < tokensToCheck.length; i += batchSize) {
        const batch = tokensToCheck.slice(i, i + batchSize);
        
        // Add timeout for each batch
        const batchPromise = Promise.all(batch.map(async (token: any) => {
          try {
            let balance = 0;
            
            if (token.address === 'native') {
              // Fetch BNB balance with timeout
              const bnbBalance = await Promise.race([
                provider.getBalance(address),
                new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), 3000))
              ]) as bigint;
              balance = Number(ethers.formatEther(bnbBalance));
            } else {
              // Fetch ERC20 token balance with timeout
              const contract = new ethers.Contract(token.address, ERC20_ABI, provider);
              const [rawBalance, decimals] = await Promise.race([
                Promise.all([
                  contract.balanceOf(address),
                  contract.decimals()
                ]),
                new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), 3000))
              ]) as [bigint, number];
              balance = Number(ethers.formatUnits(rawBalance, decimals));
            }
            
            // Only store tokens with balance > 0
            if (balance > 0) {
              newBalances[token.symbol] = balance;
              console.log(`${token.symbol} balance:`, balance);
            }
          } catch (error) {
            console.warn(`Failed to fetch balance for ${token.symbol}:`, error);
          }
        }));
        
        await batchPromise;
        
        // Small delay between batches to avoid rate limiting
        if (i + batchSize < tokensToCheck.length) {
          await new Promise(resolve => setTimeout(resolve, 100));
        }
      }
      
      // Also check balances for tokens in POPULAR_BSC_FALLBACK that weren't in the PancakeSwap list
      const tokensToCheckFromFallback = POPULAR_BSC_FALLBACK.filter(
        token => !tokenList.some((t: any) => t.symbol === token.symbol || t.address.toLowerCase() === token.address.toLowerCase())
      );
      
      // Fetch balances for fallback tokens that weren't checked
      for (const token of tokensToCheckFromFallback) {
        try {
          let balance = 0;
          
          if (token.address === 'native') {
            // BNB balance already fetched above, skip
            continue;
          } else if (token.address !== '0x0000000000000000000000000000000000000000') {
            // Only check if address is not placeholder
            const contract = new ethers.Contract(token.address, ERC20_ABI, provider);
            const [rawBalance, decimals] = await Promise.race([
              Promise.all([
                contract.balanceOf(address),
                contract.decimals()
              ]),
              new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), 3000))
            ]) as [bigint, number];
            balance = Number(ethers.formatUnits(rawBalance, decimals));
            
            if (balance > 0) {
              newBalances[token.symbol] = balance;
              console.log(`${token.symbol} balance:`, balance);
            }
          }
        } catch (error) {
          console.warn(`Failed to fetch balance for ${token.symbol}:`, error);
        }
      }
      
      // Always show popular BSC tokens, merge with real balances
      const allTokenBalances = POPULAR_BSC_FALLBACK.reduce((acc, token) => {
        acc[token.symbol] = newBalances[token.symbol] || 0;
        return acc;
      }, {} as Record<string, number>);
      
      console.log('Final balances (popular BSC tokens):', allTokenBalances);
      setBalances(allTokenBalances);
      backendWalletService.setBalances(allTokenBalances);
      
      // Fetch prices and calculate USD values
      try {
        const symbols = Object.keys(allTokenBalances).filter(s => allTokenBalances[s] > 0);
        if (symbols.length > 0) {
          const prices = await getMultipleTokenPrices(symbols);
          const newUsdValues: Record<string, number> = {};
          let totalUsd = 0;
          
          symbols.forEach(symbol => {
            const balance = allTokenBalances[symbol];
            const price = prices[symbol] || 0;
            const usdValue = balance * price;
            if (usdValue > 0) {
              newUsdValues[symbol] = usdValue;
              totalUsd += usdValue;
            }
          });
          
          setUsdValues(newUsdValues);
          setTotalBalanceUsd(totalUsd);
          console.log('Total USD balance:', totalUsd);
        } else {
          setUsdValues({});
          setTotalBalanceUsd(0);
        }
      } catch (error) {
        console.error('Error fetching prices for total balance:', error);
        setUsdValues({});
        setTotalBalanceUsd(0);
      }
      
      clearTimeout(timeoutId);
    } catch (error) {
      console.error('Failed to fetch balances:', error);
      setBalances({});
      clearTimeout(timeoutId);
    } finally {
      setIsLoadingBalances(false);
    }
  };

  // Initialize wallet connection
  const connectWallet = async () => {
    setIsLoading(true);
    try {
      // Check if wallet address is available in profile
      if (!walletAddress) {
        console.warn('No wallet address found in user profile');
        setIsLoading(false);
        return;
      }

      // Use the wallet address from user profile
      const wallet: BackendWallet = {
        address: walletAddress,
        // privateKey: "backend-managed", // This would be encrypted in production
        // mnemonic: "backend-managed" // This would be encrypted in production
      };
      
      backendWalletService.setWallet(wallet);
      setIsConnected(true);
      setAddress(wallet.address);
      
      // Fetch real balances from BSC
      await fetchRealBalances();
      
    } catch (error) {
      console.error('Failed to connect wallet:', error);
    } finally {
      setIsLoading(false);
    }
  };

  // Disconnect wallet
  const disconnect = () => {
    backendWalletService.clearWallet();
    setIsConnected(false);
    setAddress(null);
    setBalances({});
  };

  // Get token balances
  const getTokenBalances = async () => {
    if (isConnected && address && !isLoadingBalances) {
      await fetchRealBalances();
    }
    return balances;
  };

  // Get custom tokens
  const getCustomTokens = () => {
    return backendWalletService.getCustomTokens();
  };

  // Get available tokens (popular BSC tokens with real balances)
  const getAvailableTokens = () => {
    return POPULAR_BSC_FALLBACK.map(token => ({
      symbol: token.symbol,
      balance: balances[token.symbol] || 0,
      name: token.name,
      address: token.address,
      logoURI: token.logoURI,
      isReal: true // All are real BSC tokens
    }));
  };

  // Import token (simplified for backend)
  const importToken = async () => {
    // In real implementation, this would save to backend
    return true;
  };

  // Auto-connect wallet when wallet address is available
  useEffect(() => {
    const autoConnect = async () => {
      if (walletAddress && !isConnected && !isLoading) {
        await connectWallet();
      }
    };
    
    autoConnect();
  }, [walletAddress]); // Depend on walletAddress from profile


  return {
    isConnected,
    address,
    balances,
    usdValues,
    totalBalanceUsd,
    isLoading,
    isLoadingBalances,
    connectWallet,
    disconnect,
    getTokenBalances,
    getCustomTokens,
    getAvailableTokens,
    importToken,
  };
};
