// import React from 'react'

function Referral() {
  return (
    <div className="text-white">
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil obcaecati unde quod nam inventore repellat laudantium a quas, illo assumenda doloremque, recusandae ullam odio vitae nulla architecto non. Beatae necessitatibus sunt perferendis, doloremque quam voluptatem rem dolore animi amet magni, totam dolores voluptatibus! Natus facere voluptatibus autem in quos? Aliquam assumenda, repudiandae debitis voluptas temporibus totam sunt quisquam perspiciatis. Dolore amet autem eos ipsa accusamus vel alias, totam repudiandae accusantium obcaecati aspernatur minus facilis numquam aut, hic doloremque quo nulla ad placeat optio repellendus quam dicta! Neque autem quo ad perferendis repudiandae hic dolores alias natus dicta molestiae quidem illo veniam, mollitia, quae animi velit optio facilis qui incidunt, tenetur quas consequuntur pariatur! Eius totam doloremque alias repellendus id excepturi voluptate et praesentium quos non! Incidunt officiis nihil, quasi ipsum eum et voluptas voluptate adipisci dolor? Molestias deserunt aut natus saepe nobis vitae mollitia laborum eum nulla. Provident veniam laudantium qui ea ut similique id delectus eaque, molestias iste tenetur architecto repellendus maiores illo, consequuntur animi? Facere illum nostrum atque, reiciendis praesentium perferendis adipisci dolorem saepe, quisquam vitae eius debitis? Illum doloribus amet voluptas voluptates earum quae! Quae porro, minus nesciunt expedita nisi repellat excepturi et ullam perspiciatis reprehenderit sunt veritatis, perferendis vitae saepe! Enim eveniet sit velit. Maxime nemo aliquid ab quos sunt fuga hic tempora! Laborum culpa ipsam fugiat dolorem rem officiis repudiandae deleniti, suscipit animi perspiciatis? Eius similique ipsam doloremque, aspernatur quis commodi facere. Optio est odio deserunt quos ducimus nulla consectetur neque quas ea officia temporibus placeat nostrum officiis, quo vitae nihil nemo quisquam corporis suscipit quaerat, beatae itaque ad? Ducimus maiores exercitationem, eveniet minima illo vitae obcaecati neque soluta laborum itaque nostrum beatae iure dolore culpa possimus placeat iste fuga unde aut temporibus velit provident tempore. Et fugit, veniam, aliquam magni esse ratione nostrum dolorem fuga minus laboriosam explicabo deserunt a quod! Totam cumque, in dicta provident harum veniam quisquam aut saepe nobis error nihil cupiditate a quidem iusto vitae earum consectetur? Dolores repellendus laudantium excepturi modi officiis quo adipisci, quod voluptatibus eos possimus iste esse ducimus maxime quibusdam magni ipsam ut, omnis beatae porro aspernatur quam velit pariatur sunt aliquid? Voluptate esse odio non ratione soluta, recusandae cum distinctio fugiat sunt unde consectetur sint reiciendis sit labore optio natus quibusdam consequatur, ea inventore et numquam ullam aspernatur illo culpa? Mollitia consectetur ipsum, ut dolor accusamus hic deleniti voluptatibus commodi quidem recusandae qui debitis voluptas!
    
    </div>
  )
}

export default Referral
